Feature/acs 3229 rules v1 rest api get rule definition
Alfresco/alfresco-community-repo pull request #1205
Opened 2022-07-11 14:47 UTC by krdabrowski

2022-07-12 07:47 UTC, krdabrowski commented on remote-api/src/main/java/org/alfresco/rest/api/impl/RulesImpl.java
> +            return null;
Nice catch, didn't think about that - I will fix it.

2022-07-13 07:23 UTC, tpage-alfresco approved these changes
LGTM

2022-07-13 08:37 UTC, montgolfiere commented
JFYI: one test failure related to rules:

> [ERROR] Tests run: 285, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 366.768 s <<< FAILURE! - in org.alfresco.AppContext01TestSuite
> [ERROR] testIsRuleAssociatedWithRuleSet(org.alfresco.repo.rule.RuleLinkTest)  Time elapsed: 0.086 s  <<< FAILURE!
> junit.framework.AssertionFailedError
>	at org.alfresco.repo.rule.RuleLinkTest.testIsRuleAssociatedWithRuleSet(RuleLinkTest.java:403)

plus one other that might be unrelated / intermittent ?

2022-07-13 09:44 UTC, krdabrowski commented on remote-api/src/main/java/org/alfresco/rest/api/impl/RulesImpl.java
> +            return null;
After rethinking I've added a comment, as the value won't be ever used.

2022-07-13 09:59 UTC, tpage-alfresco requested changes
Please can you remove all the extra changes around Actions/Conditions from the PR. We can review those separately.

2022-07-13 10:10 UTC, krdabrowski commented on data-model/src/main/java/org/alfresco/service/namespace/NamespaceService.java
> +
Yeah... unfortunately IDE is stubborn and wont let my fix it (add there those whitespaces)

2022-07-13 10:11 UTC, krdabrowski commented on remote-api/src/main/java/org/alfresco/rest/api/impl/RulesImpl.java
> +     * @throws InvalidArgumentException if node is not of an expected type
Added to the javadoc

2022-07-13 10:12 UTC, krdabrowski commented on remote-api/src/main/java/org/alfresco/rest/api/impl/RulesImpl.java
> +     * @throws InvalidArgumentException in case of not matching associated folder node
In fact this method doesn't throw PermissionDeniedException. Read permission is only checked for folder node.

2022-07-13 10:14 UTC, krdabrowski commented on remote-api/src/test/java/org/alfresco/rest/framework/tests/core/ParamsExtender.java
> +        super(null,entityId, relationshipId, relationship2Id, passedIn, stream, addressedProperty, recognizedParams, null, mock(WebScriptRequest.class));
In tests I needed to specify relationship2Id (ruleId) - this is the only reason of this fix.

2022-07-13 10:17 UTC, krdabrowski commented on remote-api/src/main/java/org/alfresco/rest/api/impl/RulesImpl.java
> +        final NodeRef ruleSetNodeRef = validateNode(ruleSetId, ContentModel.TYPE_SYSTEM_FOLDER, "rule set");
I've replaced string literal with a constant. Unfortunately I didn't found needed string in any set/enum.

2022-07-13 10:17 UTC, tpage-alfresco approved these changes
LGTM!

2022-07-13 11:34 UTC, montgolfiere approved these changes
LGTM (subject to usual green build)

As agreed, follow-on PRs will add the the triggers, conditions, actions and other properties (for "CRU") :-)

2022-07-13 13:59 UTC, merged