Fix/mnt 22293 limit on declare version as record
Alfresco/alfresco-community-repo pull request #1208
Opened 2022-07-12 11:41 UTC by brijmohan1

2022-07-12 12:09 UTC, suneet-gupta requested changes
Please do not touch original formatting or add/remove spaces if you are not making any changes at that place.

2022-07-12 12:09 UTC, suneet-gupta commented on repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
> +            // cycleCheck(nodeId);
we shd remove commented code

2022-07-13 06:32 UTC, kavitshah-gl approved these changes
This seems fine.

2022-07-13 15:38 UTC, tpage-alfresco commented on repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml
> +        from childAssosList
Typo - "Assos"

2022-07-13 15:41 UTC, tpage-alfresco commented on repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml
> +        select assoc.id                  as id,
I'm concerned about what this returns. If we're adding a node to the root of the repository then does it return the whole repository?  What if we move a folder near the root of the repository to a new location?

2022-07-13 15:50 UTC, tpage-alfresco commented
I think the issue in general is not something that can sensibly be solved. I think to check for cycles in the general case then we have to traverse almost every parent-child relationship in the repository.

I noticed this comment:
```
     * TODO: When is it cheaper to go up and when is it cheaper to go down?
     *       Look at using direct queries to pass through layers both up and down.
```

For the problem we're trying to solve then I think we know there's no cycle because the node has no children?  If this is the case then we could solve the problem by changing the logic to do:
```
If the child has no children
  // No cycle
else
  // Perform existing check
```

This would improve performance for the majority of cases (creating a new child) and make it slightly worse when moving a folder or adding a secondary parent association to a folder.

2024-09-20 16:18 UTC, jottley commented
The related JIRA was closed as Won't Do.  Closing the PR

2024-09-20 16:18 UTC, closed without merging