Feature/repo 5395 backport new query acc optimisations
Alfresco/alfresco-community-repo pull request #152
Opened 2020-11-13 14:24 UTC by n-insaidoo

This PR represents the result of the code backport from [feature/repo-5354_demo-a](https://github.com/Alfresco/alfresco-enterprise-repo/tree/feature/repo-5354_demo-a). The new changes include: better stats reporting via API and a point of extension to support the denormalised owner column feature which is mostly implemented on the ent. repo version ([see companion PR](https://github.com/Alfresco/alfresco-enterprise-repo/pull/78)).

2020-11-19 16:40 UTC, cmshields requested changes
Nana, please see the comment about the comments.

Could you look at the failing test in AppContextExtraTestSuite and get the build green before I approve?

2020-11-19 17:42 UTC, n-insaidoo commented on repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/SingleTaskRestartableWatch.java
> +
Little oversight there, sorted it out now.

2020-11-24 09:00 UTC, n-insaidoo commented on repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/SingleTaskRestartableWatch.java
> +
@cmshields the failing tests are fixed now

2020-11-24 16:50 UTC, cmshields approved these changes
LGTM

2020-11-24 16:54 UTC, merged