Feature/apps 1722
Alfresco/alfresco-community-repo pull request #1531
Opened 2022-11-02 07:36 UTC by HylandAditya

MoveToRuleOnFoldersTest is converted .

2022-11-15 05:25 UTC, kavitshah-gl requested changes

2022-11-15 05:25 UTC, kavitshah-gl commented on amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/rules/FileAsRecordRuleTests.java
> +        inPlaceRecord = dataContent.usingUser(nonRMUser).usingResource(testFolder).createContent(CMISUtil.DocumentType.TEXT_PLAIN);
There is no checks done to make sure the file is present in unfiled records. Need to complete the test case.

2022-11-15 05:25 UTC, kavitshah-gl commented on amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/rules/FileVersionAsRecordRuleTest.java
> +
Verify if the rule has been created.

2022-11-15 05:25 UTC, kavitshah-gl commented on amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/rules/FileVersionAsRecordRuleTest.java
> +
Record should be filed as present in enterprise-share test case.

2022-11-15 05:25 UTC, kavitshah-gl commented on amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/rules/FileVersionAsRecordRuleTest.java
> +
Rule should be created using Non Rm credentials.

2022-11-15 05:25 UTC, kavitshah-gl commented on amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/rules/FileVersionAsRecordRuleTest.java
> +
Record should be filed as mentioned in Share AGS test case

2022-11-15 05:25 UTC, kavitshah-gl commented on amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/rules/FileVersionAsRecordRuleTest.java
> +    public void triggerFileVersionToRecordFolderRuleAsUserWithoutPermissions()
Remove the test case if it is only UI specific test.

2022-11-15 05:25 UTC, kavitshah-gl commented on amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/rules/FileVersionAsRecordRuleTest.java
> +    public void triggerFileVersionToRecordFolderRuleAsUserWithPermissions()
Remove the test case if it is only UI specific test.

2022-11-15 05:25 UTC, kavitshah-gl commented on amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/rules/FileVersionAsRecordRuleTest.java
> +        inPlaceRecord = dataContent.usingUser(nonRMuser).usingResource(testFolder).createContent(CMISUtil.DocumentType.TEXT_PLAIN);
Record version should be checked and then validated.

2022-11-15 05:25 UTC, kavitshah-gl commented on amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/rules/MoveToRuleOnFoldersTest.java
> +    // private final String RM_ADMIN = TEST_PREFIX + "rm_admin";
Remove commented line.

2022-11-15 05:25 UTC, kavitshah-gl commented on amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/rules/MoveToRuleOnFoldersTest.java
> +public class MoveToRuleOnFoldersTest extends BaseRMRestTest{
Refactor the entire test case.

2022-11-23 03:48 UTC, kavitshah-gl approved these changes
LGTM.

2022-11-23 08:42 UTC, merged

2022-11-23 08:42 UTC, Sbisht19 commented
merged with master branch hence closing the PR.