Feature/aca 4619 self service user password reset adw
Alfresco/alfresco-community-repo pull request #1609
Opened 2022-12-08 10:57 UTC by MohinishSah

2022-12-12 08:09 UTC, kavitshah-gl approved these changes
Changes are fine.

2022-12-13 18:36 UTC, jamalkm requested changes
From the code change, it seems we need to have a meeting to go over the requirements and resolve any misunderstanding.

2022-12-13 18:36 UTC, jamalkm commented on repository/src/main/java/org/alfresco/repo/security/authentication/ResetPasswordServiceImpl.java
> +                    createResetPasswordUrl(clientApp, id, key, userName));
Why you need to pass the userName? The username is defined in the workflow properties. 
Probably I'm missing something here, but how this method `sendResetPasswordEmail` supposed to be called? this method will not work if you don't start the workflow first (via `requestReset` method), and there you'll see that the username is added to the workflow properties.

So, based on the ACA-4619 ticket use cases:
- As a user i would like to change my password
  - I don't think this case can be covered by this service. As I mentioned you need to start the workflow first...
- As a user i would like to request to change my password at login  'forgot my password' 
  - In this case, the username is already provided and there is no need to add the username explicitly.

2022-12-13 18:36 UTC, jamalkm commented on repository/src/main/java/org/alfresco/util/UrlUtil.java
> +    public static String replaceAdwUrlPlaceholder(String value, SysAdminParams sysAdminParams)
We need to make this generic. So let's rename it to `replaceRepoBaseUrlPlaceholder`. See my comment above.

2022-12-13 18:36 UTC, jamalkm commented on repository/src/main/java/org/alfresco/repo/security/authentication/ResetPasswordServiceImpl.java
> +        if(clientApp.getName().equals("adw")) {
Apart from missing Alfresco code standard format, we shouldn't check for the specific registered-client. The client name is provided by the REST API caller, the API makes sure that the client exists, therefore, we should get all the required info from `ClientApp` object.

2022-12-13 18:36 UTC, jamalkm commented on repository/src/main/java/org/alfresco/repo/security/authentication/ResetPasswordServiceImpl.java
> +        return UrlUtil.replaceAdwUrlPlaceholder(url, sysAdminParams);
gets replaced with the generic method from the UrlUtil

2022-12-13 18:36 UTC, jamalkm commented on repository/src/main/java/org/alfresco/repo/security/authentication/ResetPasswordServiceImpl.java
> +                    .append("&id=").append(BPMEngineRegistry.createGlobalId(ActivitiConstants.ENGINE_ID, id)).append("&userName=").append(userName);
As I mentioned earlier, I don't think the userName is required.

2022-12-13 18:36 UTC, jamalkm commented on repository/src/main/java/org/alfresco/repo/security/authentication/ResetPasswordServiceImpl.java
> +            if (StringUtils.isEmpty(pageUrl)) {
`else {
  if {` should be replace with `else if ()`

2023-03-13 12:01 UTC, jamalkm requested changes

2023-03-13 12:03 UTC, jamalkm requested changes
Cloud you please add tests. I don't see any tests with this PR.

2023-03-28 06:56 UTC, kavitshah-gl approved these changes
This PR can be merged since the FE is dependent on these changes.

2023-03-28 06:56 UTC, merged

2023-04-06 18:00 UTC, jamalkm commented
This should be reverted as it is in no shape to be part of the product. FE can work with a mock service.