ACS-3975 Fix Intermittent Test Failute
Alfresco/alfresco-community-repo pull request #1785
Opened 2023-03-02 13:01 UTC by mikolajbrzezinski

2023-03-06 09:58 UTC, dsibilio requested changes
Please also remove the `Ignore` import if it's not unused as I suspect.

2023-03-06 09:59 UTC, dsibilio commented
P.S.: let's wait for the new `7.4.0-Mx` release to be completed before merging this change.

2023-03-07 08:24 UTC, damianujma approved these changes

2023-03-07 10:49 UTC, mikolajbrzezinski commented
The test was not observed to fail on the test branches, so for now it's being reintroduced. If any failures reappear then we can try to fix it, but for now it is working fine

2023-03-07 10:50 UTC, merged