File name param for direct access url requests
Alfresco/alfresco-community-repo pull request #2065
Opened 2023-07-12 14:10 UTC by canpan14

Adds optional file name parameter for all direct access url requests https://github.com/Alfresco/alfresco-community-repo/issues/2064

2023-07-12 15:50 UTC, mpichura requested changes
Nice work but for backwards compatibility please don't replace public interface methods with new ones (see my comments on the interfaces).

2023-07-12 16:24 UTC, montgolfiere reviewed
We should also have a corresponding PR ready that documents the new optional param in the OpenAPI Spec, ie. for all related endpoints / schema here:

https://github.com/Alfresco/rest-api-explorer/blob/master/src/main/webapp/definitions/alfresco-core.yaml

2023-07-12 18:50 UTC, canpan14 commented on remote-api/src/main/java/org/alfresco/rest/api/DirectAccessUrlHelper.java
> +    public String getFileName(DirectAccessUrlRequest directAccessUrlRequest)
Sure! I was just following the format of the method above.

2023-07-12 19:12 UTC, canpan14 commented
> We should also have a corresponding PR ready that documents the new optional param in the OpenAPI Spec, ie. for all related endpoints / schema here:
> 
> https://github.com/Alfresco/rest-api-explorer/blob/master/src/main/webapp/definitions/alfresco-core.yaml

Good callout, I'll get that written up.

2023-07-12 19:13 UTC, canpan14 commented on repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
> +    DirectAccessUrl requestContentDirectUrl(NodeRef nodeRef, QName propertyQName, boolean attachment, Long validFor, String fileName);
Fixed

2023-07-12 19:13 UTC, canpan14 commented on remote-api/src/main/java/org/alfresco/rest/api/Renditions.java
> +    DirectAccessUrl requestContentDirectUrl(NodeRef nodeRef, String versionId, String renditionId, boolean attachment, Long validFor, String fileName);
Fixed

2023-07-12 19:13 UTC, canpan14 commented on remote-api/src/main/java/org/alfresco/rest/api/DeletedNodes.java
> +    DirectAccessUrl requestContentDirectUrl(String archivedId, String renditionId, boolean attachment, Long validFor, String fileName);
Fixed

2023-07-12 19:13 UTC, canpan14 commented on remote-api/src/main/java/org/alfresco/rest/api/Nodes.java
> +    DirectAccessUrl requestContentDirectUrl(NodeRef nodeRef, boolean attachment, Long validFor, String fileName);
Fixed

2023-07-12 19:33 UTC, canpan14 commented
@montgolfiere PR on that project https://github.com/Alfresco/rest-api-explorer/pull/197

2023-07-13 12:37 UTC, canpan14 commented
> A couple of test failures now:
> 
> ```
> Error:  testRequestContentDirectUrl_SystemWideIsEnabledButStoreIsDisabled(org.alfresco.repo.content.ContentServiceImplUnitTest)  Time elapsed: 0.005 s  <<< ERROR!
> java.lang.StackOverflowError
> 
> Error:  testRequestContentDirectUrl_StoreIsEnabledButNotImplemented(org.alfresco.repo.content.ContentServiceImplUnitTest)  Time elapsed: 0.005 s  <<< ERROR!
> java.lang.StackOverflowError
> 
> [INFO] 
> [INFO] Results:
> [INFO] 
> Error:  Failures: 
> Error:    ContentServiceImplUnitTest.testRequestContentDirectUrl_SystemWideIsDisabled:138 unexpected exception type thrown; expected:<org.alfresco.repo.content.directurl.DirectAccessUrlDisabledException> but was:<java.lang.StackOverflowError>
> Error:  Errors: 
> Error:    ContentServiceImplUnitTest.testRequestContentDirectUrl_StoreIsEnabledButNotImplemented » StackOverflow
> Error:    ContentServiceImplUnitTest.testRequestContentDirectUrl_SystemWideIsEnabledButStoreIsDisabled » StackOverflow
> ```
> 
> I assume there's an accidental loop with the methods calling themselves now.

Whoops! Did a bad job repointing the previous interfaces. Should be fixed now.

2023-07-19 14:03 UTC, mpichura approved these changes
LGTM

2023-07-20 10:15 UTC, merged