[REPO-5440] Aspect api implementation
Alfresco/alfresco-community-repo pull request #261
Opened 2021-01-27 14:01 UTC by dhrn

https://alfresco.atlassian.net/browse/REPO-5440

depends https://github.com/Alfresco/rest-api-explorer/pull/119

2021-01-27 17:44 UTC, skopf requested changes
LGTM, just one small naming issue:
The abstract base class for the "Aspect" in the rest api package is "AbstractModel". What was the idea behind this base class? Where else are you planning to re-use this base class?
The common parent of aspects and types would be a "class" in alfresco speak. So "AbstractClass" would be a better fit.
Also I am trying to understand how you decided what parts should go into the "AbstractModel" and what parts should go into the "Aspect"

2021-01-27 20:16 UTC, gavincornwell requested changes
Nothing to add to what Stefan said except for a couple of minor coding standards items.

2021-01-27 20:16 UTC, gavincornwell commented on remote-api/src/main/java/org/alfresco/rest/api/Aspects.java
> + * Copyright (C) 2005 - 2016 Alfresco Software Limited
Please update the copyright year from 2016 to 2021, same comment for all new files below.

2021-01-27 20:16 UTC, gavincornwell commented on remote-api/src/main/java/org/alfresco/rest/api/impl/AspectsImpl.java
> +    private Collection<QName> getModelAspects(String modelId) {
Please be consistent with the coding standards of this project.

2021-01-27 20:16 UTC, gavincornwell commented on remote-api/src/main/java/org/alfresco/rest/api/impl/AspectsImpl.java
> +        if(modelId == null)
Please add a space between the if and opening bracket to be consistent with coding standards for this project.

2021-01-28 06:25 UTC, dhrn commented
Similar pattern was followed for the CMM end point. i just followed it. 

Now we have `AbstractClass` that have common properties for aspect and type. 
now it is look all the properties are same for aspect and types. 

let me know the comments
Thanks

2021-01-28 15:15 UTC, dhrn commented
Here i have adding the slack discussion for other reviewers

current representation  contains `id` `title` `descrption`  `parentId`. previously the convention was `name` `parentName` . so  i can't use the old model. so I have created the new abstract class.

As per the above  i have renamed the AbstractModel to AbstractClass. now after this Here we have two models in the same package

-  `AbstractClass.java`
-  `AbstractClassModel.java` -> used in CMM API


This is little confusing to user. so we renamed `AbstractClassModel` to `AbstractCustomClass` to keep the consistency

after that, we found the `ClassDefinition` was used in Node. so it has properties that can be shared across the 
Aspect and Type . so we have extended the `AbstractClass` from `ClassDefinition` .

here is final implementation of the [AbstractClass](https://github.com/Alfresco/alfresco-community-repo/blob/dev-dhrn-REPO-5440/remote-api/src/main/java/org/alfresco/rest/api/model/AbstractClass.java)

2021-01-28 15:37 UTC, gavincornwell approved these changes
LGTM

2021-02-02 16:27 UTC, skopf requested changes
As Jan and Gav already mentioned on the api-explorer commit, we need to be really carful with naming. Since we are using the term "prefix" for this registered namespace prefix (e.g. "cm"), we can easily confuse readers if we use this term "prefix" as well for the prefix of the namespace URI.

2021-02-02 16:33 UTC, gavincornwell requested changes

2021-02-02 16:33 UTC, gavincornwell commented on remote-api/src/main/java/org/alfresco/rest/api/impl/AbstractClassImpl.java
> +    public boolean filterByNamespace(ModelApiFilter query, QName type)
"type" is a mis-leading name for this parameter, "qname" would be better.

2021-02-02 16:33 UTC, gavincornwell commented on remote-api/src/main/java/org/alfresco/rest/api/impl/AbstractClassImpl.java
> +    static String PARAM_URI_PREFIX = "uriPrefix";
As mentioned in the review of the open api spec, this should really be "namespaceUri) as that's what we're checking see lines 82 and 86.

2021-02-02 16:33 UTC, gavincornwell commented on remote-api/src/main/java/org/alfresco/rest/api/impl/CustomModelsImpl.java
> + * Copyright (C) 2005 - 2016 Alfresco Software Limited
Remember your copyright dates ;-)

2021-02-04 19:50 UTC, gavincornwell approved these changes
LGTM

2021-02-05 08:00 UTC, skopf approved these changes

2021-02-05 09:55 UTC, merged