[REPO-5552] more filtering capablities for aspect/type api
Alfresco/alfresco-community-repo pull request #301
Opened 2021-02-19 05:27 UTC by dhrn

depends https://github.com/Alfresco/rest-api-explorer/pull/125

2021-02-19 08:57 UTC, gavincornwell requested changes

2021-02-19 08:57 UTC, gavincornwell commented on remote-api/src/main/java/org/alfresco/rest/api/impl/AspectsImpl.java
> +            logger.warn("Failed to parse Aspect " + aspectDefinition.getName().toPrefixString());
Swallowing errors at the API level is generally not a good idea, the user needs to know they made a mistake. What causes this error? It should be caught and re-thrown so the appropriate HTTP error code is returned.

2021-02-19 08:57 UTC, gavincornwell commented on remote-api/src/main/java/org/alfresco/rest/api/impl/TypesImpl.java
> +            logger.warn("Failed to parse Type" + typeDefinition.getName());
Same comment as above

2021-02-19 08:57 UTC, gavincornwell commented on remote-api/src/main/java/org/alfresco/rest/api/model/AssociationSource.java
> +  private String role = null;
Formatting looks different in this file than the others.

2021-02-22 12:37 UTC, gavincornwell requested changes
Looks good other than the missing spaces in error messages.

2021-02-22 12:37 UTC, gavincornwell commented on remote-api/src/main/java/org/alfresco/rest/api/impl/AspectsImpl.java
> +            throw new AlfrescoRuntimeException("Failed to parse Aspect" + aspectDefinition.getName());
Thanks for changing this but looks like you've lost the space in the error message.

2021-02-22 12:37 UTC, gavincornwell commented on remote-api/src/main/java/org/alfresco/rest/api/impl/TypesImpl.java
> +            throw new AlfrescoRuntimeException("Failed to parse Type" + typeDefinition.getName());
Thanks for changing this but looks like you've lost the space in the error message.

2021-02-22 20:54 UTC, gavincornwell approved these changes
LGTM

2021-02-23 09:56 UTC, eromano approved these changes

2021-02-23 09:56 UTC, merged