ACS-1711 : [SPIKE] Update the S3 connector to support Storage Classes
Alfresco/alfresco-community-repo pull request #559
Opened 2021-06-24 11:18 UTC by tzclucian

- update internal storage class representation

2021-06-24 12:07 UTC, ancutam requested changes
Update also method names in [public-services-security-context.xml](https://github.com/Alfresco/alfresco-community-repo/blob/feature/ACS-1383_StorageClasses/repository/src/main/resources/alfresco/public-services-security-context.xml#L494).

2021-06-24 12:14 UTC, tzclucian commented
> Update also method names in [public-services-security-context.xml](https://github.com/Alfresco/alfresco-community-repo/blob/feature/ACS-1383_StorageClasses/repository/src/main/resources/alfresco/public-services-security-context.xml#L494).

Done, thank you.

2021-06-28 09:13 UTC, ancutam approved these changes
Looks good. Just two minor name suggestions.

2021-06-28 09:13 UTC, ancutam commented on data-model/src/main/java/org/alfresco/repo/content/StorageClassSet.java
> + * It can have none, one, or multiple labels to specify the state
`storage classes` instead of `labels`

2021-06-28 09:13 UTC, ancutam commented on data-model/src/main/java/org/alfresco/repo/content/StorageClassSet.java
> +    public StorageClassSet(String... storageClassLabels)
`storageClasses` instead of `storageClassLabels`

2021-06-28 12:27 UTC, DenisGabriela commented on remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
> +
Please remove this comment.

2021-06-28 12:48 UTC, DenisGabriela approved these changes

2021-06-29 08:29 UTC, cristianturlica approved these changes
LGTM

2021-06-29 08:30 UTC, merged