WIP: Feature/acs 1787 endpoint for deleted nodes
Alfresco/alfresco-community-repo pull request #672
Opened 2021-08-19 11:27 UTC by mikolajbrzezinski

https://alfresco.atlassian.net/browse/ACS-1787

2021-08-23 06:56 UTC, SaraAspery requested changes
This looks really good Mikolaj! There are just a few very minor style/comment changes to make. Well done :)

2021-08-23 06:56 UTC, SaraAspery commented on remote-api/src/main/java/org/alfresco/rest/api/DeletedNodes.java
> +import org.alfresco.service.cmr.repository.NodeRef;
you can remove this line as it is an unused import

2021-08-23 06:56 UTC, SaraAspery commented on remote-api/src/main/java/org/alfresco/rest/api/DeletedNodes.java
> +    * @author Mikołaj Brzeziński
no need to add `@author` for individual methods

2021-08-23 06:56 UTC, SaraAspery commented on remote-api/src/main/java/org/alfresco/rest/api/DeletedNodes.java
> +    * Gets a presigned URL to directly access content.
maybe add a blank line between the description and the parameters

2021-08-23 06:56 UTC, SaraAspery commented on remote-api/src/main/java/org/alfresco/rest/api/DeletedNodes.java
> +        return requestContentDirectUrl(archivedId, attachment,null);
add a space between the comma and `null`

2021-08-23 06:56 UTC, SaraAspery commented on remote-api/src/main/java/org/alfresco/rest/api/DeletedNodes.java
> +
maybe remove at least 2 of these blank lines

2021-08-23 06:56 UTC, SaraAspery commented on remote-api/src/main/java/org/alfresco/rest/api/impl/DeletedNodesImpl.java
> +import org.alfresco.rest.framework.core.exceptions.DisabledServiceException;
unused import

2021-08-23 06:56 UTC, SaraAspery commented on remote-api/src/main/java/org/alfresco/rest/api/impl/DeletedNodesImpl.java
> +
remove extra blank line

2021-08-23 06:56 UTC, SaraAspery commented on remote-api/src/main/java/org/alfresco/rest/api/impl/DeletedNodesImpl.java
> +     */
you can replace these javadoc comments with:
```
    /**
     * {@inheritDoc}
     */
```
which will inherit the javadoc comments from the interface, removing the need to update in both places if/when the comments change :)

2021-08-23 06:56 UTC, SaraAspery commented on remote-api/src/main/java/org/alfresco/rest/api/impl/DeletedNodesImpl.java
> +        return nodes.requestContentDirectUrl(validatedNodeRef,attachment,validFor);
maybe just add a space between each parameter

2021-08-23 09:27 UTC, SaraAspery approved these changes

2021-08-23 10:15 UTC, merged

2021-08-24 08:30 UTC, alandavis reviewed
LGTM - nice and clean